name: flutter_aop
description: support flutter aop
version: 1.0.0
homepage: https://github.com/YangLang116/flutter_aop

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
